repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: contribute

  # A short description of the repository that will show up on GitHub
  description: ğŸ™‹ğŸ¿â€â™€ï¸ğŸ™‹ğŸ½â€â™‚ï¸ğŸ™‹ğŸ»â€â™€ï¸Contribution guide to the CNCF ecosystem

  # A URL with more information about the repository
  homepage: https://contribute.cncf.io

  # Collaborators: give specific users access to this repository.
collaborators:
  # Admins
  - username: amye
    permission: admin

  - username: idvoretskyi
    permission: admin

  - username: caniszczyk
    permission: admin

  - username: mrbobbytables
    permission: push

    # Contributors
    # all permissions except admin
  - username: carolynvs
    permission: push

  - username: jberkus
    permission: push
    
  - username: geekygirldawn
    permission: push
